---
.github/workflows/ci.yaml:
  acceptance_matrix:
    set:
      - el7
      - el8
      - ---el9
      - debian-10
      - ubuntu-2004
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1804.yml:
  delete: true
